# Project information
site_name: Peach
site_description: Доки peach 😎
site_author: GFenixL
site_url: https://gfenixl.github.io/peach-docs
docs_dir: docs
site_dir: book_src

# Copyright
copyright: Copyright &copy; 2021 GFenixL

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot

# Extras
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GFenixL
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ybEHEe8rJB
      name: Discord
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/HiIDAfNK9ks2Y2Ri
      name: Telegram

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true

#nav:
#  - 'Введение': index.ru.md
#  - 'test': test.md
  


plugins:
  - search:
      lang:
        - en
        - ru

  - i18n:
      default_language: ru
      languages:
        ru: 🇷🇺 Русский
        en: 🇬🇧 English


# Custom
nav_name: "Оглавление"

