# Project information
site_name: Peach
site_description: Доки peach 😎
site_author: GFenixL
site_url: https://gfenixl.github.io/peach-docs
docs_dir: docs
site_dir: book_src

# Copyright
copyright: Copyright &copy; 2021 GFenixL

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot

# Extras
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GFenixL
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ybEHEe8rJB
      name: Discord
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/HiIDAfNK9ks2Y2Ri
      name: Telegram

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true

nav:
  - 'Введение': index.md


extra_css:
  - css/hint.min.css


plugins:
  - search: # Default
      lang:
        - en
        - ru
  - print-site: # https://timvink.github.io/mkdocs-print-site-plugin/
      add_full_urls: false
      add_to_navigation: false
      add_table_of_contents: true
      toc_depth: 2
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      path_to_pdf: "assets/site.pdf"
  #- tooltips # https://roipoussiere.frama.io/mkdocs-tooltips/
  #- section-index # https://oprypin.github.io/mkdocs-section-index/
  # - tooltipster-links # https://github.com/midnightprioriem/mkdocs-tooltipster-links-plugin





















  # - i18n:
  #     default_language: ru
  #     languages:
  #       ru: 🇷🇺 Русский
  #       en: 🇬🇧 English


# Custom
# nav_name: "Оглавление"

